---
pid: /var/www/mdd/dev/current/tmp/pids/thin.pid
address: 127.0.0.1
timeout: 5
port: 23000
log: /var/www/mdd/dev/current/log/thin.log
max_conns: 1024
require: ['rubygems']

environment: dev
max_persistent_conns: 512
servers: 1
daemonize: true
chdir: /var/www/mdd/dev/current
